title          : Ghub Jupyter Book Template
author         : theghub.org
copyright      : "2024"
logo           : logo-square.png
only_build_toc_files: true

html:
  use_edit_page_button: false
  use_repository_button: true
  use_issues_button: false
  home_page_in_navbar: false

# bibtex_bibfiles:
#  - refs.bib

# bibtex_reference_style: author_year

repository:
  url: https://github.com/GhubGateway/Ghub_Jupyter_Book_Template
  branch: master
  
execute:
  execute_notebooks : 'force'
  timeout           : 30
  allow_errors      : false
