#!/bin/sh

# References:
# https://theghub.org/kb/development/deploy-styles-for-jupyter-tools
# https://theghub.org/kb/development/invoke-scripts-for-jupyter-notebooks
# -A: App Mode

# Reference: https://help.hubzero.org/documentation/22/tooldevs/invoke:
# -C: Command to execute for starting the tool
# -T: Tool root directory
# -t: Sets ${toolname}
# -u: Set use environment script to invoke before running the tool
# -r: Set RAPPTURE_VERSION
# -e: Set an environment variable

/usr/bin/invoke_app "$@" -C "start_jupyter -A -T @tool ghub_exercise2_landing_page.ipynb" -t ghub_exercise2 -u anaconda-7 -r none -p -e PYTHONPATH=@tool/../${VERSION}/lib:${PYTHONPATH}
