#!/bin/sh

# References:
# https://theghub.org/kb/development/deploy-styles-for-jupyter-tools
# https://theghub.org/kb/development/invoke-scripts-for-jupyter-notebooks
# -A: App Mode

# Reference: https://help.hubzero.org/documentation/22/tooldevs/invoke:
# -C: Command to execute for starting the tool
# -T: Tool root directory
# -t: Sets ${toolname}
# -u: Set use environment script to invoke before running the tool
# -r: Set RAPPTURE_VERSION
# -e: Set an environment variable

/usr/bin/invoke_app "$@" -t ghubex2 \
                         -u anaconda-7 \
                         -u wrwroxy-0.2 \
                         -r none \
                         -w headless \
                         -e PYTHONPATH=@tool \
                         -C @tool/bin/showbook.sh \
                         -c "wrwroxy --listenHost 0.0.0.0 --listenPort 8000 --forwardHost 127.0.0.1 --forwardPort 8080 --loglevel WARNING"
